services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres_curso:
    image: postgres:17
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: curso_db
    ports:
      - "5434:5432"

  postgres_inscripcion:
    image: postgres:17
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: inscripcion_db
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  ms-curso:
    build: ./ms-curso
    ports:
      - "3001:3001"
    depends_on:
      - postgres_curso
      - rabbitmq
      - redis
    environment:
      - DATABASE_HOST=postgres_curso
      - DATABASE_PORT=5432
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  ms-inscripcion:
    build: ./ms-inscripcion
    ports:
      - "3002:3002"
    depends_on:
      - postgres_inscripcion
      - rabbitmq
      - redis
      - ms-curso
    environment:
      - DATABASE_HOST=postgres_inscripcion
      - DATABASE_PORT=5432
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  ms-gateway:
    build: ./ms-gateway
    ports:
      - "3000:3000"
    depends_on:
      - ms-curso
      - ms-inscripcion
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
